apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: dvpsmesut/app:_imageTag
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: lydia-prod-postgresql-env
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lydia-prod-postgresql-env
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: lydia-prod-postgresql-env
              key: db_name
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: lydia-prod-postgresql-env
              key: host
        resources: 
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 16Mi
        ports:
        - name: http
          containerPort: 8080