apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: dvpsmesut/app:_imageTag
        imagePullPolicy: Always
        env:
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: mysql-dev-db
        - name: MYSQL_PORT_3306_TCP_PORT
          value: 3306
        - name: MYSQL_INSTANCE_NAME
          value: python_app
        - name: MYSQL_USERNAME
          value: python_app_dev_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-dev-db-user-password
              key: db_user_password
        resources: 
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 16Mi
        ports:
        - name: http
          containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 45
          timeoutSeconds: 1
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1