apiVersion: v1
kind: Service
metadata:
  name: python-app-dev
  #namespace: dev
  labels:
    app: python-app-dev
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: python-app-dev
