apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-dev
  #namespace: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: python-app-dev
  template:
    metadata:
      labels:
        app: python-app-dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node-2
      containers:
      - name: python-app-dev
        image: docker-registry.default.svc.cluster.local/python-app #:_imageTag
        env:
        - name: MYSQL_USERNAME
          value: app_dev_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-dev-db-user-password
              key: db_user_password
        - name: MYSQL_INSTANCE_NAME
          value: python_app
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: mysql-dev-db
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        resources: 
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 16Mi
        ports:
        - name: http
          containerPort: 8000