apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 32320
    - name: jnlp
      port: 50000
      nodePort: 32321
  selector:
    app: jenkins
