apiVersion: v1
kind: Service
metadata:
  name: mysql-dev-db
  labels:
    app: db-dev
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: db-dev
