
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dev-db
spec:
  selector:
    matchLabels:
      app: db-dev
  replicas: 1
  template: 
    metadata:
      labels:
        app: db-dev
    spec:
      containers:
      - name: mysql-dev-db
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-dev-db-root-password
              key: db_root_password
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-db-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-db-storage
        persistentVolumeClaim:
          claimName: mysql-db-pvc001
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config