apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    create database python_app;
    grant all privileges on python_app.* to 'python_app_dev_user'@'%' identified by '"{{ mysql_user_password.stdout_lines[0] }}"';