apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.10
    path: "/export/docker_registry"