apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home-pv001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.10
    path: "/export/mysql_db"